services:

  # ---------------------------
  # PostgreSQL
  # ---------------------------
  postgres:
    image: postgres:15
    container_name: local_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ---------------------------
  # Client Service
  # ---------------------------
  client-service:
    container_name: client-service
    build: ./client-service
    env_file:
      - .env
    environment:
      PORT: ${CLIENT_PORT}
      USER_SERVICE_URL: http://user-service:${USER_PORT}
      TOKEN_SERVICE_URL: http://token-service:${TOKEN_PORT}
      RBAC_SERVICE_URL: http://rbac-service:${RBAC_PORT}
      DATABASE_URL: ${CLIENT_DATABASE_URL}
      JWT_CLIENT_SECRET: ${JWT_CLIENT_SECRET}
      JWT_URL_SECRET: ${JWT_URL_SECRET}
    depends_on:
      - postgres
      - user-service
      - token-service
      - rbac-service

  # ---------------------------
  # User Service
  # ---------------------------
  user-service:
    container_name: user-service
    build: ./user-service
    env_file:
      - .env
    environment:
      PORT: ${USER_PORT}
      TOKEN_SERVICE_URL: http://token-service:${TOKEN_PORT}
      RBAC_SERVICE_URL: http://rbac-service:${RBAC_PORT}
      DATABASE_URL: ${USER_DATABASE_URL}
      JWT_CLIENT_SECRET: ${JWT_CLIENT_SECRET}
      JWT_URL_SECRET: ${JWT_URL_SECRET}
    depends_on:
      - postgres

  # ---------------------------
  # Token Service
  # ---------------------------
  token-service:
    container_name: token-service
    build: ./token-service
    env_file:
      - .env
    environment:
      PORT: ${TOKEN_PORT}
      USER_SERVICE_URL: http://user-service:${USER_PORT}
      DATABASE_URL: ${TOKEN_DATABASE_URL}
      JWT_CLIENT_SECRET: ${JWT_CLIENT_SECRET}
    depends_on:
      - postgres

  # ---------------------------
  # RBAC Service
  # ---------------------------
  rbac-service:
    container_name: rbac-service
    build: ./rbac-service
    env_file:
      - .env
    environment:
      PORT: ${RBAC_PORT}
      USER_SERVICE_URL: http://user-service:${USER_PORT}
      TOKEN_SERVICE_URL: http://token-service:${TOKEN_PORT}
      DATABASE_URL: ${RBAC_DATABASE_URL}
      JWT_CLIENT_SECRET: ${JWT_CLIENT_SECRET}
    depends_on:
      - postgres


  # ---------------------------
  # frontend service
  # ---------------------------
  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      PORT: ${FRONTEND_PORT}
      backend_URL: ${BACKEND_URL}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - client-service
      - user-service
      - token-service
      - rbac-service
  # ---------------------------
  # frontend service
  # ---------------------------
  nginx:
    container_name: nginx-server
    build: ./nginx
    depends_on:
      - client-service
      - user-service
      - token-service
      - rbac-service
networks:
  default:
    name: microservices-net

volumes:
  postgres_data:
