worker_processes  auto;
events{
    worker_connections 1024;
}
http{
    
    server{
        listen 80;
        server_name nginx-server;

        location = /health {
            access_log off;
            return 200 "OK\n";
        }

        location /api/AaaS/v1/{
            proxy_pass http://client-service:8000;
        }
        location /api/AaaS/rbac/v1/ {
            proxy_pass http://rbac-service:8003;
        }
        location /api/AaaS/rbac/user/v1/ {
            proxy_pass http://rbac-service:8003;
        }
        location /api/AaaS/token/v1/ {
            proxy_pass http://token-service:8002;
        }
        location /api/AaaS/user/v1/ {
            proxy_pass http://user-service:8001;
        }
    }

    server{
        listen 81;
        server_name localhost;

        location /api/AaaS/user/v1 {
            proxy_pass http://user-service:8001;
        }
    }
}